version: '3'

services:
  # managAccount
  generate-account-number:
    build: ./backend/managAccount/generateAccountNumber
    ports:
      - "3600:3600"
    networks:
      - app-network

  get-account:
    build: ./backend/managAccount/getAccount
    ports:
      - "3601:3601"
    networks:
      - app-network

  get-account-all:
    build: ./backend/managAccount/getAccountAll
    ports:
      - "3602:3602"
    networks:
      - app-network

  get-account-by-ci:
    build: ./backend/managAccount/getAccountByCI
    ports:
      - "3603:3603"
    networks:
      - app-network

  internal-transaction:
    build: ./backend/managAccount/internalTransaction
    ports:
      - "3604:3604"
    networks:
      - app-network

  save-account:
    build: ./backend/managAccount/saveAccount
    ports:
      - "3605:3605"
    networks:
      - app-network

  update-account:
    build: ./backend/managAccount/updateAccount
    ports:
      - "3606:3606"
    networks:
      - app-network

  validate-number-account:
    build: ./backend/managAccount/validateNumberAccount
    ports:
      - "3607:3607"
    networks:
      - app-network

  # managClient
  get-accounts:
    build: ./backend/managClient/getAccounts
    ports:
      - "3608:3608"
    networks:
      - app-network

  get-client:
    build: ./backend/managClient/getClient
    ports:
      - "3609:3609"
    networks:
      - app-network

  save-client:
    build: ./backend/managClient/saveClient
    ports:
      - "3610:3610"
    networks:
      - app-network

  update:
    build: ./backend/managClient/update
    ports:
      - "3611:3611"
    networks:
      - app-network

  validate-id:
    build: ./backend/managClient/validateID
    ports:
      - "3612:3612"
    networks:
      - app-network

  # managExternalTransactions
  external-transaction:
    build: ./backend/managExternalTransactions/externalTransaction
    ports:
      - "3613:3613"
    networks:
      - app-network

  verify-external-account:
    build: ./backend/managExternalTransactions/verifyexternalAccount
    ports:
      - "3614:3614"
    networks:
      - app-network

  # managMail
  confirm-transfer:
    build: ./backend/managMail/confirmTransfer
    ports:
      - "3615:3615"
    networks:
      - app-network

  forward:
    build: ./backend/managMail/forward
    ports:
      - "3616:3616"
    networks:
      - app-network

  login-failed:
    build: ./backend/managMail/loginFailed
    ports:
      - "3617:3617"
    networks:
      - app-network

  login-successful:
    build: ./backend/managMail/loginSuccessful
    ports:
      - "3618:3618"
    networks:
      - app-network

  new-temporary-credentials:
    build: ./backend/managMail/newTemporaryCredentials
    ports:
      - "3619:3619"
    networks:
      - app-network

  successful-transfer:
    build: ./backend/managMail/successfulTransfer
    ports:
      - "3620:3620"
    networks:
      - app-network

  update-mail:
    build: ./backend/managMail/update
    ports:
      - "3621:3621"
    networks:
      - app-network

  update-client-mail:
    build: ./backend/managMail/updateClient
    ports:
      - "3622:3622"
    networks:
      - app-network

  update-user-mail:
    build: ./backend/managMail/updateUser
    ports:
      - "3623:3623"
    networks:
      - app-network

  validate-mail:
    build: ./backend/managMail/validateMail
    ports:
      - "3624:3624"
    networks:
      - app-network

  verify-mail-login:
    build: ./backend/managMail/verifyMailLogin
    ports:
      - "3625:3625"
    networks:
      - app-network

  welcome-banquito:
    build: ./backend/managMail/welcomeBanquito
    ports:
      - "3626:3626"
    networks:
      - app-network

  # managUsers
  generate-code:
    build: ./backend/managUsers/generateCode
    ports:
      - "3627:3627"
    networks:
      - app-network

  get-user:
    build: ./backend/managUsers/getUser
    ports:
      - "3628:3628"
    networks:
      - app-network

  login-user:
    build: ./backend/managUsers/loginUser
    ports:
      - "3629:3629"
    networks:
      - app-network

  logout-user:
    build: ./backend/managUsers/logoutUser
    ports:
      - "3630:3630"
    networks:
      - app-network

  save-user:
    build: ./backend/managUsers/saveUser
    ports:
      - "3631:3631"
    networks:
      - app-network

  update-one-user:
    build: ./backend/managUsers/updateOneUser
    ports:
      - "3632:3632"
    networks:
      - app-network

  update-user:
    build: ./backend/managUsers/updateUser
    ports:
      - "3633:3633"
    networks:
      - app-network

  validate-answer:
    build: ./backend/managUsers/validateAnswer
    ports:
      - "3634:3634"
    networks:
      - app-network

  validate-user:
    build: ./backend/managUsers/validateUser
    ports:
      - "3635:3635"
    networks:
      - app-network

  validate-username:
    build: ./backend/managUsers/validateUsername
    ports:
      - "3636:3636"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
