name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout code.
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Configuration Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Paso 3: Login on Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: sebitas11
        password: WXTLj161

    # Paso 4: Build and upload Docker images
    - name: Build and push Docker images
      run: |
        docker build -t sebitas11/generate-account-number ./generate-account-number
        docker build -t sebitas11/get-account ./get-account
        docker build -t sebitas11/get-account-all ./get-account-all
        docker build -t sebitas11/get-account-by-ci ./get-account-by-ci
        docker build -t sebitas11/internal-transaction ./internal-transaction
        docker build -t sebitas11/save-account ./save-account
        docker build -t sebitas11/update-ccount ./update-ccount
        docker build -t sebitas11/validate-number-account ./validate-number-account
        docker build -t sebitas11/update-ccount ./update-ccount
        docker build -t sebitas11/validate-number-account ./validate-number-account

        docker push sebitas11/generate-account-number
        docker push sebitas11/get-account
        docker push sebitas11/get-account-all
        docker push sebitas11/get-account-by-ci
        docker push sebitas11/internal-transaction
        docker push sebitas11/save-account
        docker push sebitas11/update-ccount
        docker push sebitas11/validate-number-account
        docker push sebitas11/update-ccount
        docker push sebitas11/validate-number-account


    # Paso 5: Connect to the EC2 instance using elastic IP and deploy the containers
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: tuIPelastica  # iP EC2 elastic
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }} # AQUI TIENES QUE PONER TU SECRET KEY EN GITHUB -SETTINGS-SECRETN AND VARIALES-CREAR TU SECRET
        port: 22
        script: |
          # Stop and delete old containers if they exist
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
          
          # Download images from Docker Hub
          docker pull sebitas11/generate-account-number
          docker pull sebitas11/get-account
          docker pull sebitas11/get-account-all
          docker pull sebitas11/get-account-by-ci
          docker pull sebitas11/internal-transaction
          docker pull sebitas11/save-account
          docker pull sebitas11/update-ccount
          docker pull sebitas11/validate-number-account
          docker pull sebitas11/update-ccount
          docker pull sebitas11/validate-number-account

         
          # 1 
          docker run -d -p 3600:3600 \
         
            sebitas11/generate-account-number

          # 2
          docker run -d -p 3601:3601 \
         
            sebitas11/get-account
            
           # 3 
           docker run -d -p 3602:3602 \
         
            sebitas11/get-account-all 

                # 4
          docker run -d -p 3603:3603 \
         
            sebitas11/get-account-by-ci

          # 5
          docker run -d -p 3604:3604 \
         
            sebitas11/internal-transaction
            
           # 6 
           docker run -d -p 3605:3605 \
         
            sebitas11/save-account 


                # 7 
          docker run -d -p 3606:3606 \
         
            sebitas11/update-ccount

          # 8
          docker run -d -p 3607:3607 \
         
            sebitas11/validate-number-account
            
          # 9
          docker run -d -p 3623:3623 \
         
            sebitas11/update-user

          # 10
          docker run -d -p 3624:3624 \
         
            sebitas11/validate-mail